// This file will be auto-generated by Supabase CLI
// For now, we'll define basic types based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      photos: {
        Row: {
          id: string
          filename: string
          url: string
          storage_key: string
          storage_provider: string
          storage_path: string | null
          size: number | null
          width: number | null
          height: number | null
          mime_type: string | null
          uploaded_at: string
          updated_at: string
          uploaded_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          filename: string
          url: string
          storage_key: string
          storage_provider?: string
          storage_path?: string | null
          size?: number | null
          width?: number | null
          height?: number | null
          mime_type?: string | null
          uploaded_at?: string
          updated_at?: string
          uploaded_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          filename?: string
          url?: string
          storage_key?: string
          storage_provider?: string
          storage_path?: string | null
          size?: number | null
          width?: number | null
          height?: number | null
          mime_type?: string | null
          uploaded_at?: string
          updated_at?: string
          uploaded_by?: string | null
          created_at?: string
        }
      }
      tags: {
        Row: {
          id: string
          name: string
          slug: string
          color: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          color?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          color?: string | null
          created_at?: string
        }
      }
      photo_tags: {
        Row: {
          id: string
          photo_id: string
          tag_id: string
          created_at: string
        }
        Insert: {
          id?: string
          photo_id: string
          tag_id: string
          created_at?: string
        }
        Update: {
          id?: string
          photo_id?: string
          tag_id?: string
          created_at?: string
        }
      }
      google_drive_tokens: {
        Row: {
          id: string
          user_id: string
          access_token: string
          refresh_token: string | null
          expiry_date: string | null
          token_type: string | null
          scope: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          access_token: string
          refresh_token?: string | null
          expiry_date?: string | null
          token_type?: string | null
          scope?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          access_token?: string
          refresh_token?: string | null
          expiry_date?: string | null
          token_type?: string | null
          scope?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      is_token_expiring_soon: {
        Args: {
          token_expiry: string | null
        }
        Returns: boolean
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}
